import type { Metadata } from "next";
import { IBM_Plex_Mono, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

/**
 * IBM Plex, not Inter. Plex was drawn for technical and financial software
 * and its mono is metrically matched to the sans, which is what makes an
 * amount column line up against a label column without fighting.
 */
const sans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-plex-sans",
  display: "swap",
});

const mono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-plex-mono",
  display: "swap",
});

const SITE = "https://ai-finance-controller-seven.vercel.app";
const TAGLINE = "TallyProof — reconciliation that shows its work.";
const BLURB =
  "Deterministic matching, grounded AI investigation with citation verification, and a false-clear rate held at zero.";

export const metadata: Metadata = {
  // Absolute base for og:image / twitter:image, generated by the
  // opengraph-image and twitter-image routes.
  metadataBase: new URL(SITE),
  // The tab keeps the short name; the social card gets the tagline.
  title: "TallyProof",
  description:
    "Reconciliation and exception investigation across payments, settlements, bank, invoices, and ledger.",
  openGraph: {
    title: TAGLINE,
    description: BLURB,
    siteName: "TallyProof",
    type: "website",
    url: SITE,
  },
  twitter: {
    card: "summary_large_image",
    title: TAGLINE,
    description: BLURB,
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${sans.variable} ${mono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
