"""Initial schema, applied from db/schema.sql.

Revision ID: 0001
Revises:
Create Date: 2026-09-01

Why this migration executes a .sql file instead of being autogenerated:

`db/schema.sql` is the reviewed, commented source of truth for the schema,
and roughly a third of what it contains is invisible to SQLAlchemy's
autogenerate - the append-only trigger on decision_audit_events, the
split-allocation constraint trigger, the evidence-required trigger, the
partial unique index that stops one transaction being counted in two
groups, and the CHECK expressions that enforce the amount identity.

Autogenerating a migration would produce tables without the guarantees,
which is the same thing as producing the wrong schema. So the file is
applied verbatim and later migrations are hand-written deltas.
"""

from __future__ import annotations

from pathlib import Path

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

# backend/alembic/versions/0001_...py -> repo root -> db/schema.sql
SCHEMA_PATH = Path(__file__).resolve().parents[3] / "db" / "schema.sql"


def upgrade() -> None:
    if not SCHEMA_PATH.exists():
        raise FileNotFoundError(
            f"db/schema.sql not found at {SCHEMA_PATH}. "
            "It is the source of truth for this migration and must be present."
        )

    script = SCHEMA_PATH.read_text(encoding="utf-8")

    # schema.sql opens with BEGIN and closes with COMMIT so it can be run
    # standalone through psql. Alembic already holds a transaction, and a
    # nested BEGIN/COMMIT inside it would either warn or commit early, so
    # both are stripped and the migration's own transaction governs.
    stripped = "\n".join(
        line
        for line in script.splitlines()
        if line.strip().upper() not in {"BEGIN;", "COMMIT;"}
    )

    op.execute(sa.text(stripped))


def downgrade() -> None:
    # There is no meaningful partial teardown of an initial schema: the
    # objects are interdependent and dropping them in order is a script
    # that would need maintaining for no benefit. Rebuild the schema
    # instead, which is safe precisely because raw imports are preserved
    # and runs are versioned rather than mutated.
    op.execute(sa.text("DROP SCHEMA public CASCADE"))
    op.execute(sa.text("CREATE SCHEMA public"))
